"""Port for the Browser Manager (Module Specifications, Chapter 3).

Return types that would otherwise be Playwright objects (``Page``,
``BrowserContext``) are intentionally typed as ``object``: the
application layer must never import Playwright directly (ARQ-001), and
those objects must never be persisted or placed on a domain event
(PW-006).
"""

from __future__ import annotations

from typing import Protocol


class BrowserManagerPort(Protocol):
    """Controls the lifecycle of the Playwright-driven browser session.

    Only the Browser Manager adapter is authorized to hold a live
    Playwright ``Browser``/``BrowserContext``/``Page`` reference (PW-001).
    """

    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def open_url(self, url: str) -> None: ...
    def current_page(self) -> object: ...
    def current_context(self) -> object: ...
    def browser_status(self) -> str: ...
    def current_tabs(self) -> list[object]: ...
    async def wait_login(self) -> None: ...
    def is_alive(self) -> bool: ...
    async def restart(self) -> None: ...
    async def close(self) -> None: ...
