"""Port for the Element Recorder (Module Specifications, Chapter 6, 6.18)."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from snkb.domain.entities.element import Element


class ElementRecorderPort(Protocol):
    """Identifies, classifies and catalogs elements found on a page."""

    def capture_elements(self, page_id: UUID) -> list[Element]: ...
    def get_elements(self, page_id: UUID) -> list[Element]: ...
    def get_element(self, element_id: UUID) -> Element | None: ...
    def find_element(self, page_id: UUID, fingerprint: str) -> Element | None: ...
    def update_element(self, element_id: UUID) -> Element: ...
    def remove_element(self, element_id: UUID) -> None: ...
    def clear_page(self, page_id: UUID) -> None: ...
    def get_statistics(self) -> dict[str, object]: ...
