"""Port for the Export Engine (Module Specifications, Chapter 9, 9.14)."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol
from uuid import UUID


class ExportEnginePort(Protocol):
    """Consolidates data produced by every other module into the on-disk
    Knowledge Base. Never captures data itself (9.4)."""

    def export(self, session_id: UUID) -> Path: ...
    def export_session(self, session_id: UUID) -> Path: ...
    def export_navigation(self, session_id: UUID) -> Path: ...
    def export_pages(self, session_id: UUID) -> list[Path]: ...
    def export_selectors(self, session_id: UUID) -> Path: ...
    def export_statistics(self, session_id: UUID) -> Path: ...
    def export_manifest(self, session_id: UUID) -> Path: ...
    def generate_report(self, session_id: UUID) -> Path: ...
    def validate(self, session_id: UUID) -> bool: ...
    def clear_temp(self, session_id: UUID) -> None: ...
