"""Port for the Log Engine (Module Specifications, Chapter 10, 10.15)."""

from __future__ import annotations

from typing import Protocol


class LogEnginePort(Protocol):
    """Centralized, structured logging service used by every module.

    No module may write log files directly; all logging goes through this
    port (Module Specifications 10.1).
    """

    def trace(self, message: str, **context: object) -> None: ...
    def debug(self, message: str, **context: object) -> None: ...
    def info(self, message: str, **context: object) -> None: ...
    def warning(self, message: str, **context: object) -> None: ...
    def error(self, message: str, **context: object) -> None: ...
    def critical(self, message: str, **context: object) -> None: ...
    def exception(self, message: str, **context: object) -> None: ...
    def flush(self) -> None: ...
    def export(self) -> list[dict[str, object]]: ...
    def statistics(self) -> dict[str, object]: ...
