"""Port for the Navigation Recorder (Module Specifications, Chapter 5, 5.17)."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from snkb.domain.entities.navigation_edge import NavigationEdge
from snkb.domain.entities.page import Page


class NavigationRecorderPort(Protocol):
    """Builds and exposes the navigation graph of a session."""

    def start(self, session_id: UUID) -> None: ...
    def stop(self) -> None: ...
    def capture_page(self) -> Page: ...
    def update_page(self, page_id: UUID) -> Page: ...
    def close_page(self, page_id: UUID) -> None: ...
    def get_current_page(self) -> Page | None: ...
    def get_navigation_graph(self) -> list[NavigationEdge]: ...
    def get_page_history(self) -> list[Page]: ...
    def export_navigation(self) -> dict[str, object]: ...
    def clear_navigation(self) -> None: ...
