"""Port for the Screenshot Engine (Module Specifications, Chapter 8, 8.17)."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from snkb.domain.entities.screenshot import Screenshot
from snkb.domain.enums.screenshot_type import ScreenshotType


class ScreenshotEnginePort(Protocol):
    """Captures and validates visual evidence of the recorded session."""

    def capture(self, page_id: UUID, capture_type: ScreenshotType) -> Screenshot: ...
    def capture_page(self, page_id: UUID) -> Screenshot: ...
    def capture_modal(self, page_id: UUID) -> Screenshot: ...
    def capture_popup(self, page_id: UUID) -> Screenshot: ...
    def validate(self, screenshot_id: UUID) -> bool: ...
    def get_screenshot(self, screenshot_id: UUID) -> Screenshot | None: ...
    def delete(self, screenshot_id: UUID) -> None: ...
    def clear(self, page_id: UUID) -> None: ...
    def statistics(self) -> dict[str, object]: ...
