"""Port for the Selector Analyzer (Module Specifications, Chapter 7, 7.17)."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from snkb.domain.entities.selector import ElementSelectors
from snkb.domain.value_objects.selector_candidate import SelectorCandidate


class SelectorAnalyzerPort(Protocol):
    """Computes and ranks localisation strategies for captured elements."""

    def analyze(self, element_id: UUID) -> ElementSelectors: ...
    def generate(self, element_id: UUID) -> list[SelectorCandidate]: ...
    def calculate_score(self, candidate: SelectorCandidate) -> int: ...
    def get_best_selector(self, element_id: UUID) -> SelectorCandidate | None: ...
    def get_all_selectors(self, element_id: UUID) -> ElementSelectors: ...
    def validate_selector(self, element_id: UUID, candidate: SelectorCandidate) -> bool: ...
    def update_selector(self, element_id: UUID) -> ElementSelectors: ...
    def remove_selector(self, element_id: UUID, strategy: str) -> None: ...
