"""Port for the Session Manager (Module Specifications, Chapter 4, 4.16)."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from snkb.domain.entities.session import Session


class SessionManagerPort(Protocol):
    """Manages the lifecycle and metadata of a single recording session."""

    def create_session(self, instance_url: str) -> Session: ...
    def start_session(self, session_id: UUID) -> None: ...
    def pause_session(self, session_id: UUID) -> None: ...
    def resume_session(self, session_id: UUID) -> None: ...
    def finish_session(self, session_id: UUID) -> None: ...
    def cancel_session(self, session_id: UUID) -> None: ...
    def get_session(self, session_id: UUID) -> Session: ...
    def get_statistics(self, session_id: UUID) -> dict[str, object]: ...
    def update_metadata(self, session_id: UUID, metadata: dict[str, object]) -> None: ...
    def is_active(self, session_id: UUID) -> bool: ...
